### ISSUE TITLE
Container image not found

### ISSUE THREAD

**Issue by avivbintangaringga** [Gamerboy59/rpxy-webui#1]
I tried to install using docker compose but this is what I got:
![image](https://github.com/user-attachments/assets/504d4ae0-c1cf-45c9-9086-6d9b535fe46f)

My docker compose file:
![image](https://github.com/user-attachments/assets/deddd8b7-d131-4be3-b4f0-6488ea8bd70f)

**Comment by Gamerboy59** [comment]
Hi, it looks like your docker daemon tries to pull the image from a registry/repository. You'd have to build the image locally using the Dockerfile so the docker daemon can find the image locally and doesn't have to try to pull from a registry.

**Comment by avivbintangaringga** [comment]
Ahh i see. My bad. Thanks for your quick response. You might consider publishing it to the registry tho. Thanks!
